"scripts": {
		"start": "test && yarn run dev",
		"dev": "webpack-dev-server --open --config webpack.dev.js --host 0.0.0.0 --port 3000",
		"clean": "rm -rf dist && mkdir dist",
		"copy": "cp -R src/assets dist/ && cp src/* dist/",
		"prebuild": "yarn clean && mkdir -p dist/assets/graphics/ && yarn run optimize:graphics",
		"build": "webpack --config webpack.prod.js --display-error-details",
		"postbuild": "mkdir -p dist/assets/images/ && yarn run optimize:images && yarn test",
		"optimize:images": "imageOptim -d $npm_package_config_imgdist",
		"optimize:graphics": "svgo -f $npm_package_config_gfxsrc -p 0.5 --multipass --enable=removeDimensions -o $npm_package_config_gfxdist",
		"test": "size-limit",
		"test:url": "npx lighthouse --view $npm_package_config_siteurl && npx sitespeed.io $npm_package_config_siteurl && npx sonarwhal $npm_package_config_siteurl",
		"precommit": "yarn test",
		"prepush": "npm version patch"
	},